export interface PrintPdfOptions {
  title: string;
  subtitle: string;
  date: string;
  content: string; // raw HTML string for the body
}

/**
 * Opens a new browser window with print-ready HTML and triggers the print
 * dialog (which includes "Save as PDF" on all platforms).
 * No external dependencies required.
 */
export function printPdf({ title, subtitle, date, content }: PrintPdfOptions): void {
  const win = window.open('', '_blank');
  if (!win) {
    alert('Pop-up blocked. Please allow pop-ups for this site to export PDFs.');
    return;
  }

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${esc(title)}</title>
  <style>
    @page { margin: 2cm; }
    * { box-sizing: border-box; }
    body {
      font-family: Georgia, 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.6;
      color: #111;
      background: white;
      margin: 0;
      padding: 0;
    }
    .doc-header {
      border-bottom: 2px solid #111;
      padding-bottom: 12px;
      margin-bottom: 24px;
    }
    h1 { font-size: 18pt; margin: 0 0 4px; }
    .subtitle { font-size: 11pt; color: #444; margin: 0; }
    .date { font-size: 10pt; color: #666; margin-top: 4px; }
    h2 { font-size: 13pt; margin: 20px 0 8px; }
    p { margin: 0 0 12px; }
    ul { padding-left: 20px; margin: 0 0 12px; }
    li { margin-bottom: 4px; }
    table { width: 100%; border-collapse: collapse; margin-top: 12px; font-size: 10pt; }
    th { text-align: left; border-bottom: 2px solid #ccc; padding: 6px 8px; font-weight: bold; }
    td { padding: 6px 8px; border-bottom: 1px solid #eee; vertical-align: top; }
    .doc-footer {
      margin-top: 40px;
      padding-top: 12px;
      border-top: 1px solid #ccc;
      font-size: 9pt;
      color: #888;
    }
  </style>
</head>
<body>
  <div class="doc-header">
    <h1>${esc(title)}</h1>
    <p class="subtitle">${esc(subtitle)}</p>
    <p class="date">Generated ${esc(date)}</p>
  </div>
  ${content}
  <div class="doc-footer">Generated by Pulse · Edufied</div>
</body>
</html>`;

  win.document.write(html);
  win.document.close();
  win.focus();
  // Small delay lets the window finish rendering before print dialog opens
  setTimeout(() => win.print(), 300);
}

function esc(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
